site_name: BluePower
site_favicon: img/favicon.ico
repo_url: https://github.com/ModDocs/bluepower
strict: true

markdown_extensions:
  - smarty
  - urlize
  - tables
  - fenced_code

pages:
  - Home: index.md
  - Redstone:
    - Red Alloy Wire: RedAlloyWire.md
